lsi: true
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-optional-front-matter
include:
  - CONTRIBUTING.md
  - README.md
title: ibenitez's Github page
description: ibenitez's Github page description
